-- AlterTable
ALTER TABLE "User" ADD COLUMN     "engagement" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "reads" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "views" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Writing" ADD COLUMN     "engagement" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "reads" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "views" INTEGER NOT NULL DEFAULT 0;
